@extends('layouts.app')

@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ now()->format('l, F j, Y') }}</p><h1>Good things, <em>one task</em> at a time.</h1><p class="intro">Keep your day clear, focused, and moving forward.</p></div><a class="button button-primary" href="{{ route('tasks.create') }}"><span>+</span> New task</a></div>
<section class="stats" aria-label="Task summary"><div class="stat-card"><span class="stat-icon sun">&#9728;</span><div><strong>{{ $pendingCount }}</strong><span>Pending</span></div></div><div class="stat-card"><span class="stat-icon check">&#10003;</span><div><strong>{{ $completedCount }}</strong><span>Completed</span></div></div><div class="stat-card stat-card-total"><span class="stat-icon list">&#9776;</span><div><strong>{{ $tasks->count() }}</strong><span>Total tasks</span></div></div></section>
<div class="section-heading"><h2>Your tasks</h2><span>{{ $tasks->count() }} {{ Str::plural('item', $tasks->count()) }}</span></div>
@if ($tasks->isEmpty())<div class="empty-state"><div class="empty-icon">&#10024;</div><h2>Your list is clear</h2><p>Start with one small thing. You can always add more later.</p><a class="button button-primary" href="{{ route('tasks.create') }}">Create your first task</a></div>@else
<div class="task-list">@foreach ($tasks as $task)<article class="task-row {{ $task->status === 'Completed' ? 'is-complete' : '' }}"><form method="POST" action="{{ route('tasks.status', $task) }}" class="status-form">@csrf @method('PATCH')<button class="status-toggle" type="submit" aria-label="Mark {{ $task->status === 'Pending' ? 'completed' : 'pending' }}" title="Mark {{ $task->status === 'Pending' ? 'completed' : 'pending' }}"><span>{{ $task->status === 'Completed' ? '✓' : '' }}</span></button></form><div class="task-copy"><h3>{{ $task->task_name }}</h3>@if ($task->description)<p>{{ $task->description }}</p>@endif</div><div class="task-meta">@if ($task->due_date)<span class="due-date {{ $task->due_date->isPast() && $task->status === 'Pending' ? 'overdue' : '' }}">&#9679; {{ $task->due_date->format('M j, Y') }}</span>@endif<span class="status-label">{{ $task->status }}</span></div><div class="task-actions"><a href="{{ route('tasks.edit', $task) }}" aria-label="Edit {{ $task->task_name }}" title="Edit task">&#9998;</a><form method="POST" action="{{ route('tasks.destroy', $task) }}" onsubmit="return confirm('Delete this task?')">@csrf @method('DELETE')<button type="submit" aria-label="Delete {{ $task->task_name }}" title="Delete task">&#128465;</button></form></div></article>@endforeach</div>
@endif
@endsection